name: Release on Tag

on:
  push:
    tags:
      - "*"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate installer script
        env:
          MIRROR_HOST: ${{ vars.MIRROR_HOST }}
          PLUGIN_MIRROR_HOST: ${{ vars.PLUGIN_MIRROR_HOST }}
          PLUGIN_ID: ${{ vars.PLUGIN_ID }}
        run: |
          sed -i "s|__DECKY_MIRROR_HOST__|$MIRROR_HOST|g" user_install_script.sh
          sed -i "s|__DECKY_PLUGIN_MIRROR_HOST__|${PLUGIN_MIRROR_HOST}|g" user_install_script.sh
          sed -i "s|__DECKY_PLUGIN_ID__|${PLUGIN_ID}|g" user_install_script.sh
          sed -i "s|__DECKY_MIRROR_HOST__|$MIRROR_HOST|g" decky_installer.desktop

      - name: Generate checksum for decky_client.py
        run: |
          sha256sum decky_client.py > decky_client.py.sha256

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          files: |
            user_install_script.sh
            decky_client.py
            decky_client.py.sha256
            decky_installer.desktop
